
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND_OP ASSIGN ASSIGN_OP COMMA ENDMODULE IDENTIFIER INPUT LPAREN MODULE NOT_OP NUMBER OR_OP OUTPUT RPAREN SEMI WIREmodule : MODULE IDENTIFIER LPAREN id_list RPAREN SEMI declarations statements ENDMODULEid_list : IDENTIFIER \n| id_list COMMA IDENTIFIERdeclarations : declaration \n| declarations declarationdeclaration : INPUT id_list SEMI \n| OUTPUT id_list SEMI \n| WIRE id_list SEMIstatements : statement \n| statements statementstatement : ASSIGN IDENTIFIER ASSIGN_OP expression SEMIexpression : expression AND_OP expressionexpression : expression OR_OP expressionexpression : NOT_OP expressionexpression : IDENTIFIERexpression : NUMBER'
    
_lr_action_items = {'MODULE':([0,],[2,]),'$end':([1,23,],[0,-1,]),'IDENTIFIER':([2,4,8,13,14,15,19,29,32,35,36,],[3,5,10,5,5,5,25,30,30,30,30,]),'LPAREN':([3,],[4,]),'RPAREN':([5,6,10,],[-2,7,-3,]),'COMMA':([5,6,10,20,21,22,],[-2,8,-3,8,8,8,]),'SEMI':([5,7,10,20,21,22,30,31,33,37,38,39,],[-2,9,-3,26,27,28,-15,34,-16,-14,-12,-13,]),'INPUT':([9,11,12,17,26,27,28,],[13,13,-4,-5,-6,-7,-8,]),'OUTPUT':([9,11,12,17,26,27,28,],[14,14,-4,-5,-6,-7,-8,]),'WIRE':([9,11,12,17,26,27,28,],[15,15,-4,-5,-6,-7,-8,]),'ASSIGN':([11,12,16,17,18,24,26,27,28,34,],[19,-4,19,-5,-9,-10,-6,-7,-8,-11,]),'ENDMODULE':([16,18,24,34,],[23,-9,-10,-11,]),'ASSIGN_OP':([25,],[29,]),'NOT_OP':([29,32,35,36,],[32,32,32,32,]),'NUMBER':([29,32,35,36,],[33,33,33,33,]),'AND_OP':([30,31,33,37,38,39,],[-15,35,-16,35,35,35,]),'OR_OP':([30,31,33,37,38,39,],[-15,36,-16,36,36,36,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'module':([0,],[1,]),'id_list':([4,13,14,15,],[6,20,21,22,]),'declarations':([9,],[11,]),'declaration':([9,11,],[12,17,]),'statements':([11,],[16,]),'statement':([11,16,],[18,24,]),'expression':([29,32,35,36,],[31,37,38,39,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> module","S'",1,None,None,None),
  ('module -> MODULE IDENTIFIER LPAREN id_list RPAREN SEMI declarations statements ENDMODULE','module',9,'p_module','main.py',40),
  ('id_list -> IDENTIFIER','id_list',1,'p_id_list','main.py',41),
  ('id_list -> id_list COMMA IDENTIFIER','id_list',3,'p_id_list','main.py',42),
  ('declarations -> declaration','declarations',1,'p_declarations','main.py',42),
  ('declarations -> declarations declaration','declarations',2,'p_declarations','main.py',43),
  ('declaration -> INPUT id_list SEMI','declaration',3,'p_declaration','main.py',43),
  ('declaration -> OUTPUT id_list SEMI','declaration',3,'p_declaration','main.py',44),
  ('declaration -> WIRE id_list SEMI','declaration',3,'p_declaration','main.py',45),
  ('statements -> statement','statements',1,'p_statements','main.py',44),
  ('statements -> statements statement','statements',2,'p_statements','main.py',45),
  ('statement -> ASSIGN IDENTIFIER ASSIGN_OP expression SEMI','statement',5,'p_statement','main.py',45),
  ('expression -> expression AND_OP expression','expression',3,'p_expression_and','main.py',49),
  ('expression -> expression OR_OP expression','expression',3,'p_expression_or','main.py',50),
  ('expression -> NOT_OP expression','expression',2,'p_expression_not','main.py',51),
  ('expression -> IDENTIFIER','expression',1,'p_expression_id','main.py',52),
  ('expression -> NUMBER','expression',1,'p_expression_num','main.py',53),
]
